"""
Expanded historical training data parsed from openfootball repos (modern era,
2000+), per the user's request to weight full-strength tournaments.

Each row: (home, away, home_goals, away_goals, competition)
Knockout games decided on penalties are recorded at their regulation/extra-time
draw score; games decided in extra time keep the decisive a.e.t. score.

Teams not in the seed Elo table (e.g. Yugoslavia) are fine: the engine derives a
data-driven rating for every team by replaying these matches chronologically.
"""

EURO = [
    # Euro 2000
    ("Germany","Romania",1,1,"Euro"),("Portugal","England",3,2,"Euro"),
    ("Romania","Portugal",0,1,"Euro"),("England","Germany",1,0,"Euro"),
    ("England","Romania",2,3,"Euro"),("Portugal","Germany",3,0,"Euro"),
    ("Belgium","Sweden",2,1,"Euro"),("Turkey","Italy",1,2,"Euro"),
    ("Italy","Belgium",2,0,"Euro"),("Sweden","Turkey",0,0,"Euro"),
    ("Turkey","Belgium",2,0,"Euro"),("Italy","Sweden",2,1,"Euro"),
    ("Spain","Norway",0,1,"Euro"),("Yugoslavia","Slovenia",3,3,"Euro"),
    ("Slovenia","Spain",1,2,"Euro"),("Norway","Yugoslavia",0,1,"Euro"),
    ("Yugoslavia","Spain",3,4,"Euro"),("Slovenia","Norway",0,0,"Euro"),
    ("France","Denmark",3,0,"Euro"),("Netherlands","Czech Republic",1,0,"Euro"),
    ("Czech Republic","France",1,2,"Euro"),("Denmark","Netherlands",0,3,"Euro"),
    ("France","Netherlands",2,3,"Euro"),("Denmark","Czech Republic",0,2,"Euro"),
    ("Portugal","Turkey",2,0,"Euro"),("Italy","Romania",2,0,"Euro"),
    ("Netherlands","Yugoslavia",6,1,"Euro"),("France","Spain",2,1,"Euro"),
    ("Portugal","France",1,2,"Euro"),("Italy","Netherlands",0,0,"Euro"),
    ("France","Italy",2,1,"Euro"),
    # Euro 2004
    ("Portugal","Greece",1,2,"Euro"),("Spain","Russia",1,0,"Euro"),
    ("Greece","Spain",1,1,"Euro"),("Russia","Portugal",0,2,"Euro"),
    ("Spain","Portugal",0,1,"Euro"),("Russia","Greece",2,1,"Euro"),
    ("Switzerland","Croatia",0,0,"Euro"),("France","England",2,1,"Euro"),
    ("England","Switzerland",3,0,"Euro"),("Croatia","France",2,2,"Euro"),
    ("Croatia","England",2,4,"Euro"),("Switzerland","France",1,3,"Euro"),
    ("Denmark","Italy",0,0,"Euro"),("Sweden","Bulgaria",5,0,"Euro"),
    ("Bulgaria","Denmark",0,2,"Euro"),("Italy","Sweden",1,1,"Euro"),
    ("Italy","Bulgaria",2,1,"Euro"),("Denmark","Sweden",2,2,"Euro"),
    ("Germany","Netherlands",1,1,"Euro"),("Czech Republic","Latvia",2,1,"Euro"),
    ("Germany","Latvia",0,0,"Euro"),("Netherlands","Czech Republic",2,3,"Euro"),
    ("Netherlands","Latvia",3,0,"Euro"),("Germany","Czech Republic",1,2,"Euro"),
    ("Portugal","England",2,2,"Euro"),("France","Greece",0,1,"Euro"),
    ("Sweden","Netherlands",0,0,"Euro"),("Czech Republic","Denmark",3,0,"Euro"),
    ("Portugal","Netherlands",2,1,"Euro"),("Greece","Czech Republic",1,0,"Euro"),
    ("Portugal","Greece",0,1,"Euro"),
    # Euro 2008
    ("Switzerland","Czech Republic",0,1,"Euro"),("Portugal","Turkey",2,0,"Euro"),
    ("Czech Republic","Portugal",1,3,"Euro"),("Switzerland","Turkey",1,2,"Euro"),
    ("Switzerland","Portugal",2,0,"Euro"),("Turkey","Czech Republic",3,2,"Euro"),
    ("Austria","Croatia",0,1,"Euro"),("Germany","Poland",2,0,"Euro"),
    ("Croatia","Germany",2,1,"Euro"),("Austria","Poland",1,1,"Euro"),
    ("Poland","Croatia",0,1,"Euro"),("Austria","Germany",0,1,"Euro"),
    ("Romania","France",0,0,"Euro"),("Netherlands","Italy",3,0,"Euro"),
    ("Italy","Romania",1,1,"Euro"),("Netherlands","France",4,1,"Euro"),
    ("Netherlands","Romania",2,0,"Euro"),("France","Italy",0,2,"Euro"),
    ("Spain","Russia",4,1,"Euro"),("Greece","Sweden",0,2,"Euro"),
    ("Sweden","Spain",1,2,"Euro"),("Greece","Russia",0,1,"Euro"),
    ("Greece","Spain",1,2,"Euro"),("Russia","Sweden",2,0,"Euro"),
    ("Portugal","Germany",2,3,"Euro"),("Croatia","Turkey",1,1,"Euro"),
    ("Netherlands","Russia",1,3,"Euro"),("Spain","Italy",0,0,"Euro"),
    ("Germany","Turkey",3,2,"Euro"),("Russia","Spain",0,3,"Euro"),
    ("Germany","Spain",0,1,"Euro"),
    # Euro 2012
    ("Poland","Greece",1,1,"Euro"),("Russia","Czech Republic",4,1,"Euro"),
    ("Greece","Czech Republic",1,2,"Euro"),("Poland","Russia",1,1,"Euro"),
    ("Czech Republic","Poland",1,0,"Euro"),("Greece","Russia",1,0,"Euro"),
    ("Netherlands","Denmark",0,1,"Euro"),("Germany","Portugal",1,0,"Euro"),
    ("Denmark","Portugal",2,3,"Euro"),("Netherlands","Germany",1,2,"Euro"),
    ("Portugal","Netherlands",2,1,"Euro"),("Denmark","Germany",1,2,"Euro"),
    ("Spain","Italy",1,1,"Euro"),("Ireland","Croatia",1,3,"Euro"),
    ("Italy","Croatia",1,1,"Euro"),("Spain","Ireland",4,0,"Euro"),
    ("Croatia","Spain",0,1,"Euro"),("Italy","Ireland",2,0,"Euro"),
    ("France","England",1,1,"Euro"),("Ukraine","Sweden",2,1,"Euro"),
    ("Ukraine","France",0,2,"Euro"),("Sweden","England",2,3,"Euro"),
    ("England","Ukraine",1,0,"Euro"),("Sweden","France",2,0,"Euro"),
    ("Czech Republic","Portugal",0,1,"Euro"),("Germany","Greece",4,2,"Euro"),
    ("Spain","France",2,0,"Euro"),("England","Italy",0,0,"Euro"),
    ("Portugal","Spain",0,0,"Euro"),("Germany","Italy",1,2,"Euro"),
    ("Spain","Italy",4,0,"Euro"),
    # Euro 2016
    ("France","Romania",2,1,"Euro"),("Albania","Switzerland",0,1,"Euro"),
    ("Romania","Switzerland",1,1,"Euro"),("France","Albania",2,0,"Euro"),
    ("Romania","Albania",0,1,"Euro"),("Switzerland","France",0,0,"Euro"),
    ("Wales","Slovakia",2,1,"Euro"),("England","Russia",1,1,"Euro"),
    ("Russia","Slovakia",1,2,"Euro"),("England","Wales",2,1,"Euro"),
    ("Russia","Wales",0,3,"Euro"),("Slovakia","England",0,0,"Euro"),
    ("Poland","Northern Ireland",1,0,"Euro"),("Germany","Ukraine",2,0,"Euro"),
    ("Ukraine","Northern Ireland",0,2,"Euro"),("Germany","Poland",0,0,"Euro"),
    ("Northern Ireland","Germany",0,1,"Euro"),("Ukraine","Poland",0,1,"Euro"),
    ("Turkey","Croatia",0,1,"Euro"),("Spain","Czech Republic",1,0,"Euro"),
    ("Czech Republic","Croatia",2,2,"Euro"),("Spain","Turkey",3,0,"Euro"),
    ("Croatia","Spain",2,1,"Euro"),("Czech Republic","Turkey",0,2,"Euro"),
    ("Ireland","Sweden",1,1,"Euro"),("Belgium","Italy",0,2,"Euro"),
    ("Italy","Sweden",1,0,"Euro"),("Belgium","Ireland",3,0,"Euro"),
    ("Italy","Ireland",0,1,"Euro"),("Sweden","Belgium",0,1,"Euro"),
    ("Austria","Hungary",0,2,"Euro"),("Portugal","Iceland",1,1,"Euro"),
    ("Iceland","Hungary",1,1,"Euro"),("Portugal","Austria",0,0,"Euro"),
    ("Iceland","Austria",2,1,"Euro"),("Hungary","Portugal",3,3,"Euro"),
    ("Switzerland","Poland",1,1,"Euro"),("Wales","Northern Ireland",1,0,"Euro"),
    ("Croatia","Portugal",0,1,"Euro"),("France","Ireland",2,1,"Euro"),
    ("Germany","Slovakia",3,0,"Euro"),("Hungary","Belgium",0,4,"Euro"),
    ("Italy","Spain",2,0,"Euro"),("England","Iceland",1,2,"Euro"),
    ("Poland","Portugal",1,1,"Euro"),("Wales","Belgium",3,1,"Euro"),
    ("Germany","Italy",1,1,"Euro"),("France","Iceland",5,2,"Euro"),
    ("Portugal","Wales",2,0,"Euro"),("Germany","France",0,2,"Euro"),
    ("Portugal","France",1,0,"Euro"),
    # Euro 2021
    ("Turkey","Italy",0,3,"Euro"),("Wales","Switzerland",1,1,"Euro"),
    ("Turkey","Wales",0,2,"Euro"),("Italy","Switzerland",3,0,"Euro"),
    ("Switzerland","Turkey",3,1,"Euro"),("Italy","Wales",1,0,"Euro"),
    ("Denmark","Finland",0,1,"Euro"),("Belgium","Russia",3,0,"Euro"),
    ("Finland","Russia",0,1,"Euro"),("Denmark","Belgium",1,2,"Euro"),
    ("Russia","Denmark",1,4,"Euro"),("Finland","Belgium",0,2,"Euro"),
    ("Austria","North Macedonia",3,1,"Euro"),("Netherlands","Ukraine",3,2,"Euro"),
    ("Ukraine","North Macedonia",2,1,"Euro"),("Netherlands","Austria",2,0,"Euro"),
    ("North Macedonia","Netherlands",0,3,"Euro"),("Ukraine","Austria",0,1,"Euro"),
    ("England","Croatia",1,0,"Euro"),("Scotland","Czech Republic",0,2,"Euro"),
    ("Croatia","Czech Republic",1,1,"Euro"),("England","Scotland",0,0,"Euro"),
    ("Croatia","Scotland",3,1,"Euro"),("Czech Republic","England",0,1,"Euro"),
    ("Poland","Slovakia",1,2,"Euro"),("Spain","Sweden",0,0,"Euro"),
    ("Sweden","Slovakia",1,0,"Euro"),("Spain","Poland",1,1,"Euro"),
    ("Slovakia","Spain",0,5,"Euro"),("Sweden","Poland",3,2,"Euro"),
    ("Hungary","Portugal",0,3,"Euro"),("France","Germany",1,0,"Euro"),
    ("Hungary","France",1,1,"Euro"),("Portugal","Germany",2,4,"Euro"),
    ("Portugal","France",2,2,"Euro"),("Germany","Hungary",2,2,"Euro"),
    ("Wales","Denmark",0,4,"Euro"),("Italy","Austria",2,1,"Euro"),
    ("Netherlands","Czech Republic",0,2,"Euro"),("Belgium","Portugal",1,0,"Euro"),
    ("Croatia","Spain",3,5,"Euro"),("France","Switzerland",3,3,"Euro"),
    ("England","Germany",2,0,"Euro"),("Sweden","Ukraine",1,2,"Euro"),
    ("Switzerland","Spain",1,1,"Euro"),("Belgium","Italy",1,2,"Euro"),
    ("Czech Republic","Denmark",1,2,"Euro"),("Ukraine","England",0,4,"Euro"),
    ("Italy","Spain",1,1,"Euro"),("England","Denmark",2,1,"Euro"),
    ("Italy","England",1,1,"Euro"),
    # Euro 2024
    ("Germany","Scotland",5,1,"Euro"),("Hungary","Switzerland",1,3,"Euro"),
    ("Germany","Hungary",2,0,"Euro"),("Scotland","Switzerland",1,1,"Euro"),
    ("Switzerland","Germany",1,1,"Euro"),("Scotland","Hungary",0,1,"Euro"),
    ("Spain","Croatia",3,0,"Euro"),("Italy","Albania",2,1,"Euro"),
    ("Croatia","Albania",2,2,"Euro"),("Spain","Italy",1,0,"Euro"),
    ("Albania","Spain",0,1,"Euro"),("Croatia","Italy",1,1,"Euro"),
    ("Slovenia","Denmark",1,1,"Euro"),("Serbia","England",0,1,"Euro"),
    ("Slovenia","Serbia",1,1,"Euro"),("Denmark","England",1,1,"Euro"),
    ("England","Slovenia",0,0,"Euro"),("Denmark","Serbia",0,0,"Euro"),
    ("Poland","Netherlands",1,2,"Euro"),("Austria","France",0,1,"Euro"),
    ("Poland","Austria",1,3,"Euro"),("Netherlands","France",0,0,"Euro"),
    ("Netherlands","Austria",2,3,"Euro"),("France","Poland",1,1,"Euro"),
    ("Romania","Ukraine",3,0,"Euro"),("Belgium","Slovakia",0,1,"Euro"),
    ("Slovakia","Ukraine",1,2,"Euro"),("Belgium","Romania",2,0,"Euro"),
    ("Slovakia","Romania",1,1,"Euro"),("Ukraine","Belgium",0,0,"Euro"),
    ("Turkey","Georgia",3,1,"Euro"),("Portugal","Czech Republic",2,1,"Euro"),
    ("Georgia","Czech Republic",1,1,"Euro"),("Turkey","Portugal",0,3,"Euro"),
    ("Georgia","Portugal",2,0,"Euro"),("Czech Republic","Turkey",1,2,"Euro"),
    ("Switzerland","Italy",2,0,"Euro"),("Germany","Denmark",2,0,"Euro"),
    ("England","Slovakia",2,1,"Euro"),("Spain","Georgia",4,1,"Euro"),
    ("France","Belgium",1,0,"Euro"),("Portugal","Slovenia",0,0,"Euro"),
    ("Romania","Netherlands",0,3,"Euro"),("Austria","Turkey",1,2,"Euro"),
    ("Spain","Germany",2,1,"Euro"),("Portugal","France",0,0,"Euro"),
    ("England","Switzerland",1,1,"Euro"),("Netherlands","Turkey",2,1,"Euro"),
    ("Spain","France",2,1,"Euro"),("Netherlands","England",1,2,"Euro"),
    ("Spain","England",2,1,"Euro"),
]

COPA: list = []
AFCON: list = []
